# Generated by Django 4.2.11 on 2024-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassLeadersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classleader',
            name='is_kiongozi_wa_darasa',
            field=models.BooleanField(default=False),
        ),
    ]
