# Generated by Django 4.2.11 on 2024-05-02 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ClassLeadersApp', '0003_remove_classleader_is_kiongozi_wa_darasa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassLeader',
            new_name='ViongoziWaMadarasa',
        ),
    ]
