# Generated by Django 4.2.15 on 2024-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('position_winning', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Six'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth')])),
                ('zone', models.TextField(choices=[('MBEYA ZONE COMPETITION', 'MBEYA ZONE COMPETITION'), ('DODOMA ZONE COMPETITION', 'DODOMA ZONE COMPETITION'), ('MBEYA PARISH', 'MBEYA PARISH'), ('NATIONAL COMPETITION', 'NATIONAL COMPETITION')])),
                ('year', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('embed_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='KwayaVoiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice', models.CharField(choices=[('Soprano', 'Soprano'), ('Alto', 'Alto'), ('Tenor', 'Tenor'), ('Bass', 'Bass')], max_length=10)),
                ('talent', models.CharField(blank=True, choices=[('Mpiga Kinanda', 'Mpiga Kinanda'), ('Mwalimu wa Nota', 'Mwalimu wa Nota'), ('Mpiga Ngoma', 'Mpiga Ngoma'), ('Gitaa', 'Gitaa')], max_length=20, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kwaya_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KwayaMemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Ada', 'Ada')], max_length=50, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_date', models.DateField(auto_now_add=True, verbose_name='Transaction Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kwayaTransactions', to=settings.AUTH_USER_MODEL, verbose_name='Member Unique Identifier')),
            ],
            options={
                'verbose_name': 'Kwaya Malipo ya Ada',
                'verbose_name_plural': 'Kwaya Malipo ya Ada',
            },
        ),
    ]
