# Generated by Django 4.2.15 on 2024-08-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwayaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwayavoiceassignment',
            name='voice',
            field=models.CharField(choices=[('Soprano', 'Soprano (I)'), ('Alto', 'Alto (II)'), ('Tenor', 'Tenor (III)'), ('Bass', 'Bass (IV)')], max_length=10),
        ),
    ]
