# Generated by Django 4.2.11 on 2024-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwayaApp', '0002_kwayavoiceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwayavoiceassignment',
            name='talent',
            field=models.CharField(blank=True, choices=[('Mpiga Kinanda', 'Mpiga Kinanda'), ('Mwalimu wa Nota', 'Mwalimu wa Nota'), ('Mpiga Ngoma', 'Mpiga Ngoma'), ('Gitaa', 'Gitaa')], max_length=20, null=True),
        ),
    ]
