# Generated by Django 4.2.11 on 2024-05-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwayaApp', '0003_alter_kwayavoiceassignment_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('position', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Six'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth')])),
                ('year', models.IntegerField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
