# Generated by Django 4.2.11 on 2024-05-31 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kwayaApp', '0004_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='position',
            new_name='position_winning',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='description',
        ),
        migrations.AddField(
            model_name='achievement',
            name='winner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
