# Generated by Django 4.2.11 on 2024-05-31 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kwayaApp', '0005_rename_position_achievement_position_winning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='zone',
            field=models.TextField(choices=[('MBEYA ZONE COMPETITION', 'MBEYA ZONE COMPETITION'), ('DODOMA ZONE COMPETITION', 'DODOMA ZONE COMPETITION'), ('MBEYA PARISH', 'MBEYA PARISH'), ('NATIONAL LEVEL COMPETITION', 'NATIONAL LEVEL COMPETITION')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
