# Generated by Django 5.0.2 on 2024-05-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='info',
            new_name='carrier',
        ),
    ]
