# Generated by Django 4.2.15 on 2024-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matumizi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=50)),
                ('matumizi_tshirt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('matumizi_visakramenti', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('matumizi_vipeperushi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('matumizi_saloon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
            ],
            options={
                'verbose_name': 'Matumizi',
                'verbose_name_plural': 'Matumizi',
            },
        ),
        migrations.CreateModel(
            name='Mauzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=50)),
                ('mauzo_tshirt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('mauzo_visakramenti', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('mauzo_vipeperushi', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
                ('mapato_saloon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=13, null=True)),
            ],
            options={
                'verbose_name': 'Mauzo',
                'verbose_name_plural': 'Mauzo',
            },
        ),
        migrations.CreateModel(
            name='MauzoEditedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('mauzo_tshirt_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_visakramenti_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_vipeperushi_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mapato_saloon_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_tshirt_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_visakramenti_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_vipeperushi_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mapato_saloon_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mauzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MipangoNaFedhaApp.mauzo')),
            ],
        ),
        migrations.CreateModel(
            name='MauzoDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('mauzo_tshirt', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_visakramenti', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mauzo_vipeperushi', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('mapato_saloon', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatumiziEditedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_timestamp', models.DateTimeField(auto_now_add=True)),
                ('matumizi_tshirt_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_visakramenti_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_vipeperushi_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_saloon_before', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_tshirt_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_visakramenti_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_vipeperushi_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_saloon_after', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('matumizi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MipangoNaFedhaApp.matumizi')),
            ],
        ),
        migrations.CreateModel(
            name='MatumiziDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('matumizi_tshirt', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_visakramenti', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_vipeperushi', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('matumizi_saloon', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
