# Generated by Django 4.2.11 on 2024-04-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters')], max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('year_of_study', models.IntegerField(default=0)),
                ('date_posted', models.DateField()),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
