# Generated by Django 4.2.11 on 2024-05-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='level',
            field=models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters', 'Masters'), ('Doctor of Philosophy', 'Doctor of Philosophy')], max_length=50),
        ),
    ]
