# Generated by Django 4.2.15 on 2024-08-21 17:31

import AuthenticationApp.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmcsMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('namba_ya_mwanafunzi', models.CharField(max_length=20, verbose_name='Simu Student')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Your E-mail')),
                ('namba_ya_mzazi', models.CharField(max_length=20, verbose_name='Simu Parent')),
                ('ubatizo', models.CharField(choices=[('nimepata', 'NIMEPATA'), ('sijapata', 'SIJAPATA')], max_length=50, verbose_name='Ubatizo')),
                ('kipaimara', models.CharField(choices=[('nimepata', 'NIMEPATA'), ('sijapata', 'SIJAPATA')], max_length=50, verbose_name='Kipaimara')),
                ('ndoa_au_daraja', models.CharField(choices=[('nimepata', 'NIMEPATA'), ('sijapata', 'SIJAPATA')], max_length=50, verbose_name='Daraja')),
                ('elimu_uliyonayo', models.CharField(choices=[('O-level', 'O-level'), ('A-level', 'A-level'), ('Veta', 'Veta'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Masters', 'Masters')], max_length=50, verbose_name='Elimu uliyonayo')),
                ('parokia', models.CharField(max_length=100, verbose_name='Parokia')),
                ('jimbo_kuu', models.CharField(max_length=100, verbose_name='Jimbo')),
                ('course', models.CharField(choices=[('Doctor of Philosophy in Information Science and Engineering', 'Doctor of Philosophy in Information Science and Engineering'), ('Doctor of Philosophy in Mechanical Engineering', 'Doctor of Philosophy in Mechanical Engineering'), ('Doctor of Philosophy in Civil Engineering', 'Doctor of Philosophy in Civil Engineering'), ('Postgraduate Diploma in Technical Education', 'Postgraduate Diploma in Technical Education'), ('Masters of Science in Civil Engineering', 'Masters of Science in Civil Engineering'), ('Master of Engineering in Renewable Energy', 'Master of Engineering in Renewable Energy'), ('Masters of Science in Energy Engineering', 'Masters of Science in Energy Engineering'), ('Masters of Science in Information Technology', 'Masters of Science in Information Technology'), ('Masters of Engineering in Clean Energy Technology', 'Masters of Engineering in Clean Energy Technology'), ('Masters of Biodiversity Conservation', 'Masters of Biodiversity Conservation'), ('Bachelor of Science with Education', 'Bachelor of Science with Education'), ('Bachelor of Science in Natural Resources Conservation', 'Bachelor of Science in Natural Resources Conservation'), ('Bachelor of Science in Information and Communication Technology', 'Bachelor of Science in Information and Communication Technology'), ('Bachelor of Laboratory Sciences and Technology', 'Bachelor of Laboratory Sciences and Technology'), ('Bachelor of Food Science and Technology', 'Bachelor of Food Science and Technology'), ('Bachelor of Computer Science', 'Bachelor of Computer Science'), ('Bachelor of Business Administration', 'Bachelor of Business Administration'), ('Bachelor of Agribusiness Management and Technology', 'Bachelor of Agribusiness Management and Technology'), ('Bachelor of Computer Engineering', 'Bachelor of Computer Engineering'), ('Bachelor of Electrical and Electronics Engineering', 'Bachelor of Electrical and Electronics Engineering'), ('Bachelor of Mechanical Engineering', 'Bachelor of Mechanical Engineering'), ('Bachelor of Technology in Architecture', 'Bachelor of Technology in Architecture'), ('Bachelor of Civil Engineering', 'Bachelor of Civil Engineering'), ('Bachelor of Engineering in Telecommunication Systems', 'Bachelor of Engineering in Telecommunication Systems'), ('Bachelor of Technology in Landscape Architecture', 'Bachelor of Technology in Landscape Architecture'), ('Bachelor of Technical Education in Electrical and Electronics Engineering', 'Bachelor of Technical Education in Electrical and Electronics Engineering'), ('Bachelor of Technical Education in Mechanical Engineering', 'Bachelor of Technical Education in Mechanical Engineering'), ('Bachelor of Technical Education in Civil Engineering', 'Bachelor of Technical Education in Civil Engineering'), ('Bachelor of Technical Education in Architectural Technology', 'Bachelor of Technical Education in Architectural Technology'), ('Bachelor of Engineering in Data Science', 'Bachelor of Engineering in Data Science'), ('Diploma in Architecture', 'Diploma in Architecture'), ('Diploma in Biomedical Equipment Engineering', 'Diploma in Biomedical Equipment Engineering'), ('Diploma in Business Administration', 'Diploma in Business Administration'), ('Diploma in Civil Engineering', 'Diploma in Civil Engineering'), ('Diploma in Computer Engineering', 'Diploma in Computer Engineering'), ('Diploma in Electrical and Electronic Engineering', 'Diploma in Electrical and Electronic Engineering'), ('Diploma in Electronics and Telecommunication Engineering', 'Diploma in Electronics and Telecommunication Engineering'), ('Diploma in Highway Engineering', 'Diploma in Highway Engineering'), ('Diploma in Mechanical Engineering', 'Diploma in Mechanical Engineering'), ('Diploma in Mechatronics Engineering', 'Diploma in Mechatronics Engineering'), ('Diploma in Mining Engineering', 'Diploma in Mining Engineering'), ('Diploma in Computer Science', 'Diploma in Computer Science'), ('Diploma in Information and Communication Technology', 'Diploma in Information and Communication Technology'), ('Diploma in Laboratory Science and Technology', 'Diploma in Laboratory Science and Technology'), ('Diploma in Food Science and Technology', 'Diploma in Food Science and Technology'), ('Diploma in Agribusiness with Technology', 'Diploma in Agribusiness with Technology'), ('Diploma in Mechanical Engineering with Industrial Safety and Occupational Health', 'Diploma in Mechanical Engineering with Industrial Safety and Occupational Health'), ('Diploma of Technical Education in Civil Engineering', 'Diploma of Technical Education in Civil Engineering'), ('Diploma of Technical Education in Electrical and Electronics Engineering', 'Diploma of Technical Education in Electrical and Electronics Engineering'), ('Diploma of Technical Education in Architectural Technology', 'Diploma of Technical Education in Architectural Technology'), ('Diploma of Technical Education in Mechanical Engineering', 'Diploma of Technical Education in Mechanical Engineering'), ('Diploma of Business Administration in Accounting and Finance', 'Diploma of Business Administration in Accounting and Finance'), ('Diploma of Business Administration in Marketing and Entrepreneurship', 'Diploma of Business Administration in Marketing and Entrepreneurship'), ('Diploma in Mechatronic Engineering', 'Diploma in Mechatronic Engineering'), ('Diploma in Business Computing', 'Diploma in Business Computing'), ('Diploma in Automotive and Autoelectrical Engineering', 'Diploma in Automotive and Autoelectrical Engineering'), ('Certificate in Agribusiness with Technology', 'Certificate in Agribusiness with Technology'), ('Certificate in Business Administration', 'Certificate in Business Administration')], max_length=100, verbose_name='Course')),
                ('department', models.CharField(choices=[('Department of Construction Management and Technology', 'Department of Construction Management and Technology'), ('Department of Architecture and Art Design', 'Department of Architecture and Art Design'), ('Department of Urban Planning and Real Estate Studies', 'Department of Urban Planning and Real Estate Studies'), ('Department of Information System and Technology', 'Department of Information System and Technology'), ('Department of Computer Science and Engineering', 'Department of Computer Science and Engineering'), ('Department of Electronics and Telecommunication Engineering', 'Department of Electronics and Telecommunication Engineering'), ('Department of Content Engineering and Multimedia Technology', 'Department of Content Engineering and Multimedia Technology'), ('Department of Informatics', 'Department of Informatics'), ('Department of Civil Engineering', 'Department of Civil Engineering'), ('Department of Geoscience and Mining Technology', 'Department of Geoscience and Mining Technology'), ('Department of Electrical and Power Engineering', 'Department of Electrical and Power Engineering'), ('Department of Mechanical and Industrial Engineering', 'Department of Mechanical and Industrial Engineering'), ('Department of Chemical Processing and Environmental Engineering', 'Department of Chemical Processing and Environmental Engineering'), ('Department of Applied Science', 'Department of Applied Science'), ('Department of Mathematics and Statistics', 'Department of Mathematics and Statistics'), ('Department of Natural Science', 'Department of Natural Science'), ('Department of Medical Science and Technology', 'Department of Medical Science and Technology'), ('Department of Technical Education', 'Department of Technical Education'), ('Department of Earth Sciences', 'Department of Earth Sciences'), ('Department of Business Management', 'Department of Business Management'), ('Department of Humanities', 'Department of Humanities'), ('Department of Law', 'Department of Law'), ('Department of Agricultural Engineering', 'Department of Agricultural Engineering'), ('Department of Crop Science and Horticulture', 'Department of Crop Science and Horticulture'), ('Department of Food Science and Technology', 'Department of Food Science and Technology'), ('Department of Natural Resources', 'Department of Natural Resources'), ('Department of Veterinary Medicine and Animal Science', 'Department of Veterinary Medicine and Animal Science'), ('Department of Agronomy and Soil Science', 'Department of Agronomy and Soil Science')], max_length=100, verbose_name='Department')),
                ('college', models.CharField(choices=[('College of Engineering and Technology', 'College of Engineering and Technology (CET)'), ('College of Science and Technical Education', 'College of Science and Technical Education (CoSTE)'), ('College of Humanities and Business Studies', 'College of Humanities and Business Studies (CoHBS)'), ('College of Architecture and Construction Technology', 'College of Architecture and Construction Technology (CoACT)'), ('College of Information and Communication Technology', 'College of Information and Communication Technology (CoICT)'), ('College of Agricultural Sciences and Technology', 'College of Agricultural Sciences and Technology (CoAST)')], max_length=100, verbose_name='College')),
                ('level_of_study', models.CharField(choices=[('Doctor of Philosophy', 'Doctor of Philosophy'), ('Postgraduate Diploma', 'Postgraduate Diploma'), ('Masters', 'Masters'), ("Bachelor's Degree", "Bachelor's Degree"), ('Diploma', 'Diploma'), ('Certificate', 'Certificate')], max_length=20, verbose_name='Level unayosoma')),
                ('vyama_vya_kitume', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LEGIO MARIA', 'LEGIO MARIA'), ('KARISMATIKI', 'KARISMATIKI'), ('KWAYA', 'KWAYA'), ('MOYO MTAKATIFU WA YESU', 'MOYO MTAKATIFU WA YESU'), ('WATUMISHI WA ALTARE', 'WATUMISHI WA ALTARE'), ('WASOMA MASOMO', 'CHAMA CHA WASOMA MASOMO')], max_length=100, verbose_name='Utume')),
                ('vinginevyo', models.CharField(blank=True, max_length=100, verbose_name='Vinginevyo')),
                ('tarehe_aliyosajiliwa', models.DateTimeField(auto_now_add=True)),
                ('years_of_study', models.IntegerField(blank=True, null=True, verbose_name='Years of Study')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_mwenyekiti_tawi', models.BooleanField(default=False)),
                ('is_katibu_tawi', models.BooleanField(default=False)),
                ('is_mhazini_tawi', models.BooleanField(default=False)),
                ('is_mwenyekiti_legio', models.BooleanField(default=False)),
                ('is_katibu_legio', models.BooleanField(default=False)),
                ('is_mhazini_legio', models.BooleanField(default=False)),
                ('is_mwenyekiti_kwaya', models.BooleanField(default=False)),
                ('is_katibu_kwaya', models.BooleanField(default=False)),
                ('is_mhazini_kwaya', models.BooleanField(default=False)),
                ('is_mwenyekiti_karismatiki', models.BooleanField(default=False)),
                ('is_katibu_karismatiki', models.BooleanField(default=False)),
                ('is_mhazini_karismatiki', models.BooleanField(default=False)),
                ('is_mwenyekiti_moyo_mtakatifu_wa_Yesu', models.BooleanField(default=False)),
                ('is_katibu_moyo_mtakatifu_wa_Yesu', models.BooleanField(default=False)),
                ('is_mhazini_moyo_mtakatifu_wa_Yesu', models.BooleanField(default=False)),
                ('is_kiongozi_wa_darasa', models.BooleanField(default=False)),
                ('is_mwenyekiti_litrujia', models.BooleanField(default=False)),
                ('is_katibu_litrujia', models.BooleanField(default=False)),
                ('is_mwenyekiti_mipango_na_fedha', models.BooleanField(default=False)),
                ('is_katibu_mipango_na_fedha', models.BooleanField(default=False)),
                ('is_mhazini_mipango_na_fedha', models.BooleanField(default=False)),
                ('is_mwenyekiti_mas_media', models.BooleanField(default=False)),
                ('is_katibu_mas_media', models.BooleanField(default=False)),
                ('is_mhazini_mas_media', models.BooleanField(default=False)),
                ('is_mwenyekiti_sherehe_na_maafa', models.BooleanField(default=False)),
                ('is_katibu_sherehe_na_maafa', models.BooleanField(default=False)),
                ('is_mhazini_sherehe_na_maafa', models.BooleanField(default=False)),
                ('is_mwenyekiti_michezo_na_burudani', models.BooleanField(default=False)),
                ('is_katibu_michezo_na_burudani', models.BooleanField(default=False)),
                ('is_mhazini_michezo_na_burudani', models.BooleanField(default=False)),
                ('is_mwenyekiti_muziki', models.BooleanField(default=False)),
                ('is_katibu_muziki', models.BooleanField(default=False)),
                ('is_mhazini_muziki', models.BooleanField(default=False)),
                ('is_mwenyekiti_elimu_ushauri_na_nidhamu', models.BooleanField(default=False)),
                ('is_katibu_elimu_ushauri_na_nidhamu', models.BooleanField(default=False)),
                ('is_mhazini_elimu_ushauri_na_nidhamu', models.BooleanField(default=False)),
                ('is_registration_committee', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Tmcs Members',
            },
            managers=[
                ('objects', AuthenticationApp.models.CustomUserManager()),
            ],
        ),
    ]
