# Generated by Django 4.2.11 on 2024-05-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcsmember',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Your E-mail'),
        ),
    ]
