# Generated by Django 4.2.11 on 2024-05-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_alter_tmcsmember_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LEGIO MARIA', 'LEGIO MARIA'), ('KARISMATIKI', 'KARISMATIKI'), ('KWAYA', 'KWAYA'), ('MOYO MTAKATIFU WA YESU', 'MOYO MTAKATIFU WA YESU'), ('WATUMISHI WA ALTARE', 'WATUMISHI WA ALTARE'), ('WASOMA MASOMO', 'CHAMA CHA WASOMA MASOMO')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='tmcsmember',
            name='vyama_vya_kitume',
        ),
        migrations.AddField(
            model_name='tmcsmember',
            name='vyama_vya_kitume',
            field=models.ManyToManyField(blank=True, to='AuthenticationApp.association', verbose_name='Utume'),
        ),
    ]
