# Generated by Django 4.2.15 on 2024-08-19 13:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0004_remove_tmcsmember_vyama_vya_kitume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmcsmember',
            name='vyama_vya_kitume',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LEGIO MARIA', 'LEGIO MARIA'), ('KARISMATIKI', 'KARISMATIKI'), ('KWAYA', 'KWAYA'), ('MOYO MTAKATIFU WA YESU', 'MOYO MTAKATIFU WA YESU'), ('WATUMISHI WA ALTARE', 'WATUMISHI WA ALTARE'), ('WASOMA MASOMO', 'CHAMA CHA WASOMA MASOMO')], max_length=100, verbose_name='Utume'),
        ),
    ]
