# Generated by Django 4.2.15 on 2024-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderYaTMCSTawiPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_title', models.CharField(default='Calender Ya TMCS Tawi', max_length=100)),
                ('pdf_file', models.FileField(upload_to='calender_ya_tawi/')),
            ],
            options={
                'verbose_name': 'Calenda ya Tawi',
                'verbose_name_plural': 'Calenda ya Tawi',
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafasi_ya_uongozi', models.CharField(max_length=255)),
                ('jina_la_kiongozi', models.CharField(max_length=255)),
                ('picha_ya_kiongozi', models.ImageField(upload_to='committee_members/')),
                ('kozi_anayosoma', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Viongozi Kamati Kuu',
                'verbose_name_plural': 'Viongozi Kamati Kuu',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event Title', max_length=300)),
                ('event_date', models.DateField(help_text='Event Date')),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matukio yajayo',
                'verbose_name_plural': 'Matukio yajayo',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadersTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('level', models.CharField(choices=[('National Leader', 'National Leader'), ('Zonal Leader', 'Zonal Leader'), ('Branch Leader', 'Branch Leader')], max_length=50)),
                ('start_year', models.PositiveIntegerField(default=2024)),
                ('end_year', models.PositiveIntegerField(default=2024)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MasomoyaDominika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dominika', models.CharField(max_length=300)),
                ('somo_la1', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('somo_la2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('injili', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Masomo ya Misa',
                'verbose_name_plural': 'Masomo ya Misa',
            },
        ),
        migrations.CreateModel(
            name='MaswalinaMajibu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('swali', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('jibu', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Maswali na Majibu',
                'verbose_name_plural': 'Maswali na Majibu',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Matangazo',
                'verbose_name_plural': 'Matangazo',
            },
        ),
        migrations.CreateModel(
            name='Novena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novena_name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('novena_image', models.ImageField(blank=True, null=True, upload_to='novena_images/')),
            ],
            options={
                'verbose_name': 'Novena',
                'verbose_name_plural': 'Novena',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_quote', models.TextField()),
                ('author_of_quote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rozary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozary_name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('rozary_image', models.ImageField(blank=True, null=True, upload_to='rozary_images/')),
            ],
            options={
                'verbose_name': 'Rozary',
                'verbose_name_plural': 'Rozary',
            },
        ),
        migrations.CreateModel(
            name='SaintLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_saint', models.CharField(max_length=100, verbose_name='Saint Name')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Date of Death')),
                ('biography', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='saint_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Maisha ya Watakatifu',
                'verbose_name_plural': 'Maisha ya Watakatifu',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galery events',
                'verbose_name_plural': 'Galery events',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('community_image', models.ImageField(blank=True, null=True, upload_to='community_images/')),
                ('patron_saint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='religionApp.saintlife')),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Community',
            },
        ),
    ]
