# Generated by Django 4.2.11 on 2024-05-28 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('religionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='patron_saint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='religionApp.saintlife'),
        ),
    ]
