# Generated by Django 4.2.15 on 2024-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Ada', 'Ada'), ('Zaka', 'Zaka'), ('Tunisha mfuko', 'Tunisha mfuko'), ('Sherehe na Maafa', 'Sherehe na Maafa'), ('Cheti', 'Cheti')], max_length=50, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('transaction_date', models.DateField(auto_now_add=True, verbose_name='Transaction Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Member Unique Identifier')),
            ],
            options={
                'verbose_name': 'Michango ya Chama',
                'verbose_name_plural': 'Michango ya Chama',
            },
        ),
    ]
