# Generated by Django 4.2.15 on 2024-08-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sadaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=50)),
                ('sadaka1', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('shukrani', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
            ],
            options={
                'verbose_name': 'Sadaka',
                'verbose_name_plural': 'Sadaka',
            },
        ),
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('sadaka1', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shukrani', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
